project:
  type: website
  output-dir: docs

website:
  title: "Arda TÃ¼rkan's Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/ardaturkan
      - icon: linkedin
        href: https://www.linkedin.com/in/ardaturkan/

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
  html:
    toc: true
    theme: 
      light: pulse 
      dark: superhero
    css: styles.css
    grid: 
      sidebar-width: 300px
      body-width:	900px
      margin-width: 300px
      gutter-width: 1.5rem
      


editor: visual

